[package]
name = "diener"
version = "0.2.0"
authors = ["Bastian KÃ¶cher <git@kchr.de>"]
edition = "2018"
categories = [ "command-line-utilities" ]
documentation = "https://docs.rs/diener"
repository = "https://github.com/bkchr/diener"
keywords = [ "cli", "substrate", "polkadot" ]
license = "Apache-2.0/MIT"
description = """
dependency diener is a tool for easily changing [Substrate](https://github.com/paritytech/substrate) or [Polkadot](https://github.com/paritytech/polkadot) dependency versions
"""
readme = "./README.md"

[dependencies]
structopt = "0.3.17"
walkdir = "2.3.1"
git-url-parse = "0.2.0"
toml_edit = "0.2.0"
cargo_metadata = "0.12.3"
