[package]
name = "diener"
version = "0.4.2"
authors = ["Bastian KÃ¶cher <git@kchr.de>"]
edition = "2018"
categories = [ "command-line-utilities" ]
documentation = "https://docs.rs/diener"
repository = "https://github.com/bkchr/diener"
keywords = [ "cli", "substrate", "polkadot" ]
license = "Apache-2.0/MIT"
description = """
dependency diener is a tool for easily changing [Substrate](https://github.com/paritytech/substrate), [Polkadot](https://github.com/paritytech/polkadot) or [BEEFY](https://github.com/paritytech/grandpa-bridge-gadget) dependency versions
"""
readme = "./README.md"

[dependencies]
structopt = "0.3.23"
walkdir = "2.3.2"
git-url-parse = "0.3.1"
toml_edit = "0.2.1"
cargo_metadata = "0.14.0"
env_logger = "0.9.0"
log = "0.4.14"
